# Numpy Stack Lecture 1

In [1]:
import numpy as np

In [2]:
L=[1, 2, 3] # This is a Python List

In [3]:
A = np.array([1, 2, 3]) # This is a numpy array

In [4]:
for e in L:
    print(e)

1
2
3


#### A List can add components using ```.append``` function

In [5]:
L.append(4) # append() works for a List

In [6]:
L

[1, 2, 3, 4]

#### While a numpay array cannot use ```.append``` function

In [7]:
A.append(4) # Not working for numpy.array

AttributeError: 'numpy.ndarray' object has no attribute 'append'

#### List can also use "+" to append element, but numpy arrary cannot

In [8]:
L = L + [5] # '+' acts like concatenate

In [9]:
print(L)

[1, 2, 3, 4, 5]


# Heading 1
##  Heading 2
###  Heading 3
#### Heading 4

In [10]:
A = A + [5, 6] # '+' is adding the number in the numpy.array

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

#### '+' operator acts very differently for List and numpy Array...

In [11]:
A + A

array([2, 4, 6])

In [12]:
2 * A

array([2, 4, 6])

In [13]:
2 * L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [14]:
L ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [15]:
A**2

array([1, 4, 9], dtype=int32)

In [16]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [17]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [18]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Concatenate Numpy Arrays

In [19]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6]])
C = np.concatenate((a, b), axis=0) # pay attention to the axis option


In [20]:
np.concatenate((a, b.T), axis=1) # pay attention to the axis option

array([[1, 2, 5],
       [3, 4, 6]])

In [21]:
np.concatenate((a, b), axis=None) # when "axis= None", make it a linear array

array([1, 2, 3, 4, 5, 6])

In [22]:
x = np.arange(8.0) # up to but not including 8
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [23]:
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [24]:
 x = np.arange(7.0)  # up to but not including 7
np.array_split(x, 3)
    

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.])]

## Dot product of two arrays

In [25]:
a = np.array([1, 2])
b = np.array([3, 4])

In [26]:
dot = 0.0
for e, f in zip(a, b):
    dot += e*f
print (dot)

11.0


In [27]:
a*b

array([3, 8])

In [28]:
np.sum(a*b)

11

# The Dot Product
 $a \cdot b = a^T b = \sum^{D}_{d=1}a_db_d $

In [29]:
np.dot(a,b) # == aTb

11

In [30]:
a.dot(b)

11

$||a||_2$

In [31]:
amag = np.sqrt((a*a).sum())

In [32]:
amag

2.23606797749979

In [33]:
np.linalg.norm(a)

2.23606797749979

In [34]:
cosangle = a.dot(b)/(np.linalg.norm(a) * np.linalg.norm(b))

In [35]:
cosangle

0.9838699100999074

In [36]:
angle = np.arccos(cosangle)

In [37]:
angle

0.17985349979247847

# Comparisons for numpy operations vs. regular for-loops
Reference: [Why you should forget loops and embrace vectorization for Data Science](https://www.experfy.com/blog/why-you-should-forget-loops-and-embrace-vectorization-for-data-science/)

In [38]:
# https://deeplearningcourses.com/c/deep-learning-prerequisites-the-numpy-stack-in-python
# https://www.udemy.com/deep-learning-prerequisites-the-numpy-stack-in-python

from __future__ import print_function, division
from builtins import range
# Note: you may need to update your version of future
# sudo pip install -U future


import numpy as np
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

# dot product using regular for-loop
t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

# dot product using numpy built-in dot function
t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0
print ("Time to run regular loop =>  ", dt1.total_seconds())
print ("Time to run numpy dot product => ", dt2.total_seconds())
print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

Time to run regular loop =>   4.556049
Time to run numpy dot product =>  0.080001
dt1 / dt2: 56.94990062624217


In [39]:
M = np.array([[1, 2], [3, 4]])

In [40]:
L = [[1, 2], [3,4]]

In [41]:
M[0,0]

1

In [42]:
M2 = np.matrix([[1, 2], [3, 4]])

In [43]:
M2

matrix([[1, 2],
        [3, 4]])

In [44]:
A = np.array(M2)

In [45]:
A

array([[1, 2],
       [3, 4]])