# Numpy Stack Lecture 2

In [ ]:
#! pip install jupyter_contrib_nbextensions
#! jupyter contrib nbextension install --system

In [1]:
import numpy as np

# Generate numpy arrarys

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

#### Generate 10 zeros in a vector
**Bold** face, _this_

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**10x10 matrix with zeros**

In [5]:
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

a 10x10 matrix of 1's

In [6]:
O = np.ones((10,10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### a 5x5 identity matrix

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.ones(10)*3

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

a 10 elements vector of 3's

In [9]:
np.arange(5,21).reshape(4,4)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [12]:
np.arange(5,21).reshape(4,4)/20.0

array([[0.25, 0.3 , 0.35, 0.4 ],
       [0.45, 0.5 , 0.55, 0.6 ],
       [0.65, 0.7 , 0.75, 0.8 ],
       [0.85, 0.9 , 0.95, 1.  ]])

#### Generate a 5x5 matrix with ~uniform(0,1)

In [14]:
1 + np.random.random((5, 5))*4

array([[3.33890584, 3.77391689, 3.01229916, 3.37394108, 1.49922206],
       [3.80300809, 1.8686981 , 3.57737519, 4.23365165, 3.48317297],
       [4.25456583, 1.2286742 , 2.14236355, 4.65311022, 4.43006289],
       [2.46955899, 2.14569118, 2.29373457, 4.2862622 , 1.80114106],
       [1.80549831, 4.00563591, 2.59402199, 1.84121156, 2.1195555 ]])

In [18]:
mu = 3.0
std = 2.0
G = mu + np.random.randn(5, 5) * std 
G

array([[-0.41713985,  2.25339833,  5.71773226,  3.41394921,  2.70345   ],
       [ 2.27245822,  3.94278374,  2.7309457 ,  5.58397156,  1.67008582],
       [ 6.54591025,  4.00978704,  4.54604574,  1.82202222,  3.00342223],
       [ 0.56454667,  4.39997855,  3.39031509,  5.02361696,  3.88391976],
       [ 4.62661148,  4.6879412 ,  1.04729421,  3.5942497 ,  1.94723542]])

In [19]:
G.mean()

3.3185812610510768

In [20]:
G.var()

2.7335610727330804

# Matrix Products

In [22]:
A =np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [23]:
Ainv = np.linalg.inv(A)

In [24]:
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

$AA^{-1} = I$

In [25]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [26]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [27]:
np.dot(A,Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [28]:
np.linalg.det(A)

-2.0000000000000004

In [29]:
np.diag(A)

array([1, 4])

In [30]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

In [ ]:
np.outer(a, b)

In [ ]:
np.inner(a, b)

In [31]:
np.diag(A).sum()

5

In [32]:
np.trace(A)

5

In [34]:
X = np.random.randn(100,3)
X

array([[-1.13049147, -0.14360532, -0.11283263],
       [ 0.07330605,  0.5346988 , -0.25898564],
       [-0.71509146,  0.37178425, -0.00795641],
       [-0.68353377,  1.28154925, -1.46097825],
       [ 0.17641728, -1.90799034, -1.13840054],
       [ 1.1361862 , -1.29765927, -1.122631  ],
       [ 0.50072808,  0.27262511,  0.36666003],
       [ 1.64210531, -0.71651844, -0.51714852],
       [-0.78410098,  1.03022739, -0.91403402],
       [ 0.92308251, -1.40078204,  0.39995314],
       [ 0.5717471 , -0.30197747,  0.08562577],
       [ 0.43607081,  0.36653018, -0.57633535],
       [-0.53146593, -1.18493885,  0.06884505],
       [ 1.60804137,  0.15464809, -0.96639537],
       [-1.15703282, -0.41856264,  0.50534144],
       [-1.18503167, -0.92128081,  0.53146185],
       [-1.4717166 , -0.86595833, -1.14177892],
       [ 0.74059458, -0.21515544, -0.71747626],
       [ 0.78914644, -1.74797699, -0.83104673],
       [ 0.90865339,  0.36382026,  1.73487917],
       [ 0.35075727, -0.35533981,  0.508

In [35]:
cov = np.cov(X.T) # Transpose the X matrix first for convariance calculations

In [36]:
cov

array([[ 0.92172576, -0.08038441,  0.03784426],
       [-0.08038441,  0.91109294, -0.1520931 ],
       [ 0.03784426, -0.1520931 ,  0.71963679]])

In [37]:
np.linalg.eigh(cov)

(array([0.63552939, 0.86255242, 1.05437368]),
 array([[ 0.02166242,  0.8309595 , -0.55591101],
        [ 0.48794153,  0.47653248,  0.73132063],
        [ 0.87260748, -0.28709424, -0.3951368 ]]))

In [38]:
np.linalg.eig(cov)

(array([1.05437368, 0.86255242, 0.63552939]),
 array([[ 0.55591101, -0.8309595 ,  0.02166242],
        [-0.73132063, -0.47653248,  0.48794153],
        [ 0.3951368 ,  0.28709424,  0.87260748]]))

# Solving a linear system

Problem: $Ax=b$ <br>
Solution: $A^{-1}Ax= A^{-1}b$

In [39]:
A

array([[1, 2],
       [3, 4]])

In [41]:
b = [3, 6]

In [42]:
x = np.linalg.inv(A).dot(b)

In [43]:
x

array([8.8817842e-16, 1.5000000e+00])

In [44]:
np.linalg.solve(A, b)

array([2.96059473e-16, 1.50000000e+00])

In [45]:
A = np.array([[1, 1],[1.5, 4]])

In [46]:
b = np.array([2200, 5050])

In [47]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [ ]:
X=[]

In [ ]:
import numpy as np
import csv

## Read datasets from a .csv file

In [ ]:
with open("data_2d.csv", 'r') as f:
    X = list(csv.reader(f, delimiter=","))
X  

In [ ]:
type(X) # X is a list not a numpy.array

#### Convert X to a numpy.arrary

In [ ]:
X= np.array(X)

In [ ]:
X

## One can easily read a .csv file using Pandas Library

In [ ]:
import pandas as pd

In [ ]:
X2 = pd.read_csv("data_2d.csv", header= None)

In [ ]:
type(X2)

In [ ]:
X2.info()

In [ ]:
X2.describe()

### We will have lectures on Pandas separately, see you later!!!